---
  - name: SO FAMILY REDHAT
    include_tasks: /etc/ansible/roles/uxxi_sstt_samba/src/roles/linux-smb-enroll/tasks/redhat.yml
    when: ansible_os_family == 'RedHat'

  - name: SO FAMILY UBUNTU
    include_tasks: /etc/ansible/roles/uxxi_sstt_samba/src/roles/linux-smb-enroll/tasks/ubuntu.yml
    when: ansible_os_family == 'Debian'

