---
# we use docker as plateform
driver:
  name: vagrant

# We use Inspec as testing framework
verifier:
  name: inspec
  inspec_tests:
    - path: tests/inspec

platforms:
  # Provisioning of Ansible server where ansible playbook will be launched
  - name: centos-7
    driver:
      network:
        - [ 'private_network', { ip: '172.28.128.10' } ]
    provisioner:
      name: ansible_playbook
      ansible_connection: ssh
      ansible_inventory: tests/solaris/inventory/hosts
      require_chef_for_busser: false
      ansible_host_key_checking: false
      idempotency_test: true
      playbook: tests/solaris/test.yml
    verifier:
      name: shell
      command: echo 'Skipping Verify'

  # Test on Solaris 11
  - name: solaris-11
    driver:
      box: jonatasbaldin/solaris11
      provision: false
      network:
        - [ 'private_network', { ip: '172.28.128.11' } ]
      vagrantfiles:
        - tests/vagrant/vagrant_solaris_target.rb
    provisioner:
      name: shell

suites:
  - name: default
