---
- name: Converge
  hosts: all
  become: True
  gather_facts: True
  tasks:
    - import_role:
        name: ansible_role_rh_satellite_managed_host
      vars:
        rh_satellite_managed_host_molecule_dummy: True

...
