---
  - name: SO FAMILY REDHAT
    include_tasks: /etc/ansible/roles/uxxi_sstt_ldaps/src/roles/linux-ldaps-enroll/tasks/redhat.yml
    when: ansible_os_family == 'RedHat'

  - name: SO FAMILY UBUNTU
    include_tasks: /etc/ansible/roles/uxxi_sstt_ldaps/src/roles/linux-ldaps-enroll/tasks/ubuntu.yml
    when: ansible_os_family == 'Debian'

