- hosts: all
  gather_facts: no
  tasks:
    - set_fact:
        rem_user: "{{ ansible_user | default(lookup('env','USER')) }}"
        rem_host: "{{ ansible_host }}"
    - local_action: command ssh-copy-id {{ rem_user }}@{{ rem_host }}
    - setup:
    - selinux:
        state: disabled

#para id_rsa de root o del usurio donde estes
