#!/bin/bash
#echo " inicio copy"
#sshpass -f passw ssh-copy-id -i /root/.ssh/id_rsa root@agentforeman.redocu.lan
#sleep 4
#echo "fin del copy"
#echo "ssh agent y ssh-add"
#eval `ssh-agent`
#ssh-add /root/.ssh/id_rsa
#bash -i # or other session starter

for server in `cat server.txt`;
do
    sshpass -f passw.txt ssh-copy-id -i /root/.ssh/id_rsa.pub -o StrictHostKeyChecking=no root@$server
    #sshpass -p "oracle" ssh-copy-id -i /home/deploy/id_rsa.pub root@$server
done
sleep 4
echo "fin del copy"
echo "ssh agent y ssh-add"
eval `ssh-agent`
ssh-add /root/.ssh/id_rsa.pub
bash -i # or other session starter

