---
  - name: Centos
    include_tasks: /etc/ansible/roles/uxxi_sstt_foreman-master/src/roles/foreman-enroll/tasks/so/centos.yml
    when: ansible_facts['distribution'] == 'CentOS' and ansible_distribution_major_version == '7'
   
  - name: Centos
    include_tasks: /etc/ansible/roles/uxxi_sstt_foreman-master/src/roles/foreman-enroll/tasks/so/centos8.yml
    when: ansible_facts['distribution'] == 'CentOS' and ansible_distribution_major_version == '8'
 
  - name: Oracle
    include_tasks: /etc/ansible/roles/uxxi_sstt_foreman-master/src/roles/foreman-enroll/tasks/so/oracle.yml
    when: ansible_facts['distribution']  == 'OracleLinux' and ansible_distribution_major_version == '7'

  - name: RedHat
    include_tasks: /etc/ansible/roles/uxxi_sstt_foreman-master/src/roles/foreman-enroll/tasks/so/redhat.yml
    when: ansible_facts['distribution']  == 'RedHat'

  - name: Ubuntu
    include_tasks: /etc/ansible/roles/uxxi_sstt_foreman-master/src/roles/foreman-enroll/tasks/so/ubuntu.yml
    when: ansible_facts['distribution']  == 'Ubuntu'
   
  - name: Amazon
    include_tasks: /etc/ansible/roles/uxxi_sstt_foreman-master/src/roles/foreman-enroll/tasks/so/amazon.yml
    when: ansible_facts['distribution']  == 'Amazon'

  - name: Oracle8
    include_tasks: /etc/ansible/roles/uxxi_sstt_foreman-master/src/roles/foreman-enroll/tasks/so/oracle8.yml
    when: ansible_facts['distribution']  == 'OracleLinux' and ansible_distribution_major_version == '8'

