---
- name: Gather packages
  package_facts:
    manager: auto
  ignore_errors: yes

- name: MENSAJE
  debug:
    msg:
      - '- COMPROBAR SI subscription-manager ESTA INSTALADO'

- name: check if subscription-manager is installed
  shell:  rpm -qa | grep subscription-manager
  register: sub_installed
  ignore_errors: True
  check_mode: False
  changed_when: False

- name: subscription-manager IS INSTALLED
  debug:
    msg: "subscription-manager is installed"
  when: sub_installed.rc == 0

- name: subscription-manager NOT INSTALLED
  debug:
    msg: "subscription-manager not installed"
  when: sub_installed.rc == 1

- name: MENSAJE
  when: sub_installed.rc == 1
  debug:
    msg:
      - '- subscription-manager NO ESTA INSTALADO NO SE PUEDE ELMINAR DEL REGISTRO'

- name: subscription-manager remove
  when: sub_installed.rc == 0
  shell: subscription-manager remove --all
  register: remove
  ignore_errors: yes

- debug: msg="{{remove.stdout_lines}}"

- name: subscription-manager unregister
  when: sub_installed.rc == 0
  shell:  subscription-manager unregister
  register: unregister
  ignore_errors: yes

- debug: msg="{{unregister.stderr_lines}}"

- name: subscription-manager clean
  when: sub_installed.rc == 0
  shell: subscription-manager clean
  register: clean
  ignore_errors: yes

- debug: msg="{{clean.stdout_lines}}"

- name: borrar cahce de yum
  when: sub_installed.rc == 0
  shell: rm -rf /var/cache/yum/*

- name: yum clean all
  when: sub_installed.rc == 0
  shell: yum clean all

- name: yum clean metadato
  when: sub_installed.rc == 0
  shell: yum clean metadata

- name: yum makecache msg
  when: sub_installed.rc == 0
  debug:
    msg:
      - '- Tarda unos minutos yum makecache'

- name: yum makecache
  when: sub_installed.rc == 0
  shell: yum makecache

- name: yum repolist all
  when: sub_installed.rc == 0
  shell: yum repolist all
  register: repolist

- debug: msg="{{repolist.stdout_lines}}"

- name: Upgrade all packages
  yum:
    name: sudo
    state: latest
  register: update

#- debug: msg="{{update.stdout_lines}}"

##################################################
############ Config Repo #########################


- name: EDIT REPO ORACLE LINUX 7
  when: ansible_distribution == 'OracleLinux' and ansible_distribution_major_version >= '7' and ansible_distribution_major_version < '8'
  copy:
    src: templates/oracle-linux-ol7.repo
    dest: /etc/yum.repos.d/
    owner: root
    group: root
    mode: 0644
    backup: yes
  tags:
    - ol7

- name: EDIT REPO ORACLE LINUX 8
  when: ansible_distribution == 'OracleLinux' and ansible_distribution_major_version >= '8' and ansible_distribution_major_version < '9'
  copy:
    src: templates/oracle-linux-ol8.repo
    dest: /etc/yum.repos.d/
    owner: root
    group: root
    mode: 0644
    backup: yes
  tags:
    - ol8

- name: EDIT REPO CENTOS 7
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version >= '7' and ansible_distribution_major_version < '8'
  copy:
    src: templates/CentOS-Base.repo
    dest: /etc/yum.repos.d/
    owner: root
    group: root
    mode: 0644
    backup: yes
  tags:
    - c7

- name: EDIT REPO CENTOS 8
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version >= '8' and ansible_distribution_major_version < '9'
  copy:
    src: "{{ item }}"
    dest: /etc/yum.repos.d/
    owner: root
    group: root
    mode: 0644
    backup: yes
  with_items:
    - templates/CentOS-Base8.repo
    - templates/CentOS-Extras8.repo
    - templates/CentOS-AppStream8.repo
  tags:
    - c8
  register: C8

- name: yum repolist all
  shell: yum repolist all
  register: repolist2

- debug: msg="{{repolist2.stdout_lines}}"
