---
# tasks file for ansible-role-puppet
# conexion a los otros main SO repositorio agente
- name: Include OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install Puppetlabs repository
  include_tasks: "repository/install-repository.yml"
  when: install_from == "puppetlabs_repository"

- name: Install puppet-agent
  include_tasks: "agent/agent.yml"
  when: puppet_agent_install
