---
# add Puppetlabs repository in Debian

- name: Debian | Add Puppetlabs apt key
  apt_key:
    url: https://apt.puppetlabs.com/DEB-GPG-KEY-puppet
    state: present
  when: ansible_distribution == "Debian" and ansible_distribution_major_version >= '08'

- name: old Debian | Add Puppetlabs apt key for old Debian
  shell: |
    set -o pipefail
    curl -s https://apt.puppetlabs.com/DEB-GPG-KEY-puppet | apt-key add - > /etc/apt/trusted.gpg.d/puppetlabs.output
  args:
    creates: /etc/apt/trusted.gpg.d/puppetlabs.output
  when: ansible_distribution == "Debian" and ansible_distribution_major_version < '08'

- name: Debian | Add Puppetlabs repository
  apt_repository:
    repo: deb http://apt.puppetlabs.com {{ ansible_distribution_release }} puppet{{ puppet_version }}
    state: present

- name: Debian | Add Puppetlabs source repository
  apt_repository:
    repo: deb-src http://apt.puppetlabs.com {{ ansible_distribution_release }} puppet{{ puppet_version }}
    state: "{{ puppetlabs_repo_source }}"

- name: Debian | Update apt cache
  apt:
    update_cache: yes
  changed_when: false
