---
# add Puppetlabs repository in Amazonlinux

- name: Amazonlinux | Add Puppetlabs repository
  yum_repository:
    name: puppet{{ puppet_version }}
    description: "Puppet {{ puppet_version }} Repository el {{ ansible_distribution_major_version }} - $basearch"
    baseurl: http://yum.puppetlabs.com/puppet{{ puppet_version }}/el/{{ ansible_distribution_major_version|int + 5 }}/$basearch
    gpgcheck: true
    gpgkey: https://yum.puppet.com/RPM-GPG-KEY-puppet
    enabled: true
    state: present

- name: Amazonlinux | Add Puppetlabs source repository
  yum_repository:
    name: puppet{{ puppet_version }}-source
    description: "Puppet {{ puppet_version }} Repository el {{ ansible_distribution_major_version }} - Source"
    baseurl: http://yum.puppetlabs.com/puppet{{ puppet_version }}-nightly/el/{{ ansible_distribution_major_version|int + 5 }}/SRPMS
    gpgcheck: true
    gpgkey: https://yum.puppet.com/RPM-GPG-KEY-puppet
    enabled: true
    state: "{{ puppetlabs_repo_source }}"
