---
# add Puppetlabs repository in Opensuse Leap

- name: Suse | Add Puppetlabs rpm key
  rpm_key:
    state: present
    key: https://yum.puppet.com/RPM-GPG-KEY-puppet

- name: Suse | Add Puppetlabs repository
  zypper_repository:
    name: puppet{{ puppet_version }}
    description: Puppet {{ puppet_version }} Repository sles 12 - $basearch
    repo: http://yum.puppetlabs.com/puppet{{ puppet_version }}/sles/12/$basearch
    auto_import_keys: yes
    state: present
  changed_when: false

- name: Suse | Add Puppetlabs source repository
  zypper_repository:
    name: puppet{{ puppet_version }}
    description: Puppet {{ puppet_version }} Repository sles 12 - Source
    repo: http://yum.puppetlabs.com/puppet{{ puppet_version }}-nightly/sles/12/SRPMS
    auto_import_keys: yes
    state: "{{ puppetlabs_repo_source }}"
  changed_when: false
