---
  - name: SO FAMILY REDHAT
    include_tasks: /etc/ansible/roles/uxxi_db_samba/roles/tasks/redhat.yml
    when: ansible_os_family == 'RedHat'

  - name: SO FAMILY UBUNTU
    include_tasks: /etc/ansible/roles/uxxi_db_samba/roles/tasks/ubuntu.yml
    when: ansible_os_family == 'Debian'

